name: CIformatterr

#on:
#  push:
 #   branches: master 
#  pull_request: 
#    branches: master
  
#jobs:
  #build_formatter:
  #  runs-on: ubuntu-latest
  #  steps:
      #- uses: actions/checkout@v3
      #- name: build_hello
      #  run: |
      #    cd 
       #   cmake 
          
      #- name: build_solver
       # run: |
